version: '2'

services:
  excursion:
    build:
        context: .
        dockerfile: ./excursions-excursions/docker/Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - postgres
    links:
      - postgres

  user:
    build:
        context: .
        dockerfile: ./excursions-users/docker/Dockerfile
    ports:
      - 8070:8070
    depends_on:
      - postgres
    links:
      - postgres

  place:
    build:
        context: .
        dockerfile: ./excursions-places/docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    build:
        context: .
        dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'store'
    #volumes:
        #- /shared_folder/postgresql:/var/lib/postgresql
        #- ./db-init-scripts:/docker-entrypoint-initdb.d
        #- ./usr/local/bin/init-user-db.sh

#container_name: postgres_items

